# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    jdkArchitectureOption: 'x64'
    goals: 'package'
- script: mvn -v

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/target/surefire-reports/*.xml'
- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: 'target/site/jacoco/jacoco.xml'
    pathToSources: 'src/main/java/com/training/example/JacocoExample'
